import { Button, HStack, Image, Stack, Text, VStack } from "@chakra-ui/react";
import keccak256 from "keccak256";
// import client from "@walletconnect/sign-client";
import Head from 'next/head';
import { useEffect } from 'react';
import { Navbar } from "../components/Navbar";
import { useWallet } from "../hooks/useWallet";

export default function Home() {
    const { client } = useWallet();
    useEffect(() => {
        console.log(client);
        // else { client.killSession && client.killSession(); }
    }, [client]);

    useEffect(() => {
        console.log('signing');
        console.log(client);
        // Check if connection is already established
        if (client.connected) {

            const message = "My email is john@doe.com - 1537836206101";
            const address = client.accounts[0];
            console.log(client.accounts);
            const msgParams = [
                address,
                // keccak256("\x19Ethereum Signed Message:\n" + message.length + message)
                `0x${keccak256("\x19Ethereum Signed Message:\n" + message.length + message)}`

            ];

            console.log(msgParams);

            // Sign message
            client
                .signPersonalMessage(msgParams)
                .then((result) => {
                    // Returns signature.
                    console.log(result);
                })
                .catch(error => {
                    // Error returned when rejected
                    console.error(error);
                });

            // Get provided accounts and chainId
            console.log(client);

        }

    }, [client]);
    return (
        <div >
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Navbar></Navbar>
                <VStack h="100vh" w="100vw"
                    className="bg" justifyContent="space-between" spacing="24px" alignItems="center">
                    <Stack h="64px" w="100vw"></Stack>
                    <Image src="./spiritusmin.svg" alt="" w="48%" h="auto"
                    />
                    <Button h="100px" w="300px"
                        borderRadius="12px" backgroundColor="#3FD1FF"
                        fontFamily="Poppins, Arial, sans-serif"
                        fontSize="32px"
                    > Demo</Button>
                    <HStack h="36px" w="100vw" backgroundColor="#3FD1FF" alignItems="center" justifyContent="space-evenly">
                        <Text color="white">learn more </Text>
                        <Text color="white">learn more </Text>
                        <Text color="white">learn more </Text>
                        <Text color="white">learn more </Text>
                        <Text color="white">learn more </Text>
                        <Text color="white">learn more </Text>
                        <Text color="white">learn more </Text>
                        <Text color="white">learn more </Text>
                        <Text color="white">learn more </Text>
                        <Text color="white">learn more </Text>
                        <Text color="white">learn more </Text>

                    </HStack>
                </VStack>
                <VStack h="100vh" w="100vw"
                    backgroundColor="white" justifyContent="space-around" spacing="0px" alignItems="center">
                    words
                </VStack>

            </main>

            {/* <footer className={styles.footer}>
            </footer> */}
        </div >
    );
}
